version: '1.0.{build}'
configuration:
#  - Debug
  - Release
platform: Any CPU
hosts:
  api.nuget.org: 93.184.221.200
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
services:
  - mongodb
init:
  - ps: $Env:BUILD = "$($Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0"))"
before_build:
  - appveyor-retry dotnet restore NoAdsHere.sln --configfile Nuget/Nuget.Config
build_script:
  - dotnet build "NoAdsHere\NoAdsHere.csproj" -c %CONFIGURATION% --no-dependencies
  - dotnet build "UnitTests\UnitTests.csproj" -c %CONFIGURATION% --no-dependencies
test_script:
  - ps: dotnet test UnitTests\UnitTests.csproj -c Release --no-build --logger Appveyor
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/noadshere/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path 'UnitTests\result.xml')