version: '1.0.{build}'
configuration:
  - Debug
  - Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
  - appveyor-retry dotnet restore -v Minimal NoAdsHere.sln
build_script:
  - dotnet build "NoAdsHere\NoAdsHere.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
  - dotnet build "UnitTests\UnitTests.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
