version: '2'

services:
  noadshere:
    image: noadshere
    build:
      context: ./NoAdsHere
      dockerfile: Dockerfile
    depends_on:
      - database
      
  database:
    image: mongo:latest
    command: "--smallfiles"
    ports:
      - 27017:27017