version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
      - ./Nuget/Nuget.Config:/src/Nuget/Nuget.Config
    working_dir: /src
    command: /bin/bash -c "dotnet restore --configfile ./Nuget/Nuget.Config ./NoAdsHere.sln  && dotnet publish ./NoAdsHere.sln -c Release -o ./obj/Docker/publish"
    #entrypoint: tail -f /dev/null